<template>
    <h1 class="text-center font-montserrat font-extralight text-5xl my-10">
      Customer Policies
    </h1>
  <section class="max-w-6xl mx-auto py-10 px-4 mb-20 ">
<div class="flex flex-col lg:flex-row">
   <div class="bg-[#f5f5f5] px-3 md:px-7 lg:px-10 min-w-[300px] py-4 rounded-md" >
    <nav class="flex flex-col">
  <div v-for="(head, index) in heads" :key="index" class="mb-3">
    <button
      @click="setActiveHead(index)"
      class="pb-3 font-medium text-lg font-lato text-left"
      :class="{
        'text-[#76a543]': activeHead === index,
        'text-gray-800': activeHead !== index,
      }"
    >
      {{ head }}
    </button>

    <!-- Show details below nav item (only sm & md) -->
    <div
      v-if="activeHead === index"
      class="lg:hidden bg-[#f5f5dc57] px-4 lg:px-8 py-4 mt-2 rounded"
    >
      <h4 class="font-montserrat text-2xl font-medium">Policy Details</h4>
      <p class="font-lato text-[16px] tracking-wide text-gray-500 mt-4 leading-8">
        {{ details[index].message }}
      </p>
    </div>
  </div>
</nav>
   </div>
  <div
      v-if="details[activeHead]"
      class="hidden lg:block  bg-[#f5f5dc57] px-8 py-4  rounded"
    >
      <h4 class="font-montserrat text-2xl font-medium">Policy Details</h4>
      <p class="font-lato text-[16px] tracking-wide text-gray-500 mt-4 leading-8">
        {{ details[activeHead].message }}
      </p>
    </div>

    
 
</div>

  </section>
</template>

<script>
export default {
  name: "Policies",
  data() {
    return {
      activeHead: 0, // default first tab active
      heads: [
        "Policies",
        "Wallet Recharge Offer Policy",
        "Subscription Timing",
        "Vacation Timing",
        "Doorstep Cancellation Policy",
        "Communication Guidelines",
        "Bottle Breakage Policy",
        "Referral Credit Policy",
        "Change of Address",
        "Low Balance Policy",
        "Subscription End Date",
        "Milk Delivery Issue",
        "Requesting Wallet Balance for Account Closure",
      ],
      details: [
        {
          message:
            "Customers must create a subscription for next-day delivery by 7 p.m. Cancellations / Changes made to your subscription for the next day, after 7 p.m. will not be activated, as the delivery chart would have been generated by then.",
        },
        {
          message:
            "We used to have an offer where customers who make a certain amount of recharge will get additional amount in extra. This is subject to change. App payments will not be affected in anyways, ONLY the OFFER amount will be subject to change.",
        },
        {
          message:
            "Customers must create a subscription for next-day delivery by 7 p.m. Cancellations / Changes made to your subscription for the next day, after 7 p.m. will not be activated, as the delivery chart would have been generated by then.",
        },
        {
          message:
            "If you don't need milk, please create a vacation request in the app before 7 PM for the next day's delivery. For urgent situations, you can contact our customer care team — they will do their best to support you...",
        },
        {
          message:
            "Doorstep cancellation is not allowed and you will be charged for the product.",
        },
        {
          message:
            "Please do not communicate pausing your subscription or vacations through your delivery agent... Please only communicate these issues through your dealer or the UB Mobile App.",
        },
        {
          message:
            "We don't charge for the first bottle breakage. After that, we charge ₹30 for a one-litre bottle and ₹25 for a half-litre bottle.",
        },
        {
          message:
            "Get ₹200 on your respective UB Wallet. Without a Referral Code, it is not possible to get wallet rewards as it is an automated process.",
        },
        {
          message:
            "If a customer relocates, they must submit an app feedback or speak with customer service. Please avoid directly updating the location in the app as it might disturb the delivery chain.",
        },
        {
          message:
            "If your wallet balance is insufficient for your next day delivery, it will automatically switch to a Pause Status. To get a milk delivery for the next day, you must top up your wallet before 7 p.m...",
        },
        {
          message:
            "To end your Milk Subscription, you must have an Active Subscription. If you have a wallet balance but don't have an active subscription, milk will not be delivered.",
        },
        {
          message:
            "If you have not received your milk delivery, with an active subscription, please inform us before 9 a.m. on the same day.",
        },
        {
          message: "Please refer to the Refund Policy page.",
        },
      ],
    };
  },
  methods: {
    setActiveHead(index) {
      this.activeHead = index;
    },
  },
};
</script>
